name: Deploy Angular to VPS (Apache) Para Examen Segundo Trimestre

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app-series-examen

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          # Opcional: ayuda al caché si usas subcarpetas
          cache-dependency-path: app-series-examen/package-lock.json

      - run: npm ci
      - run: npm run build -- --configuration production

      # Esto te servirá para depurar y ver si la carpeta se creó bien
      - name: Inspect dist
        run: |
          echo "Listando contenido de dist..."
          ls -la dist
          ls -la dist/app-series-examen || true
          ls -la dist/app-series-examen/browser || true

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: app-series-examen/dist/app-series-examen/browser/
          remote_path: ${{ secrets.VPS_PATH }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
          remote_key_pass: ${{ secrets.VPS_REMOTE_KEY_PASS }}